package asimovrpc

import (
	"math/big"
)

type AsimovAPI interface {
	Web3ClientVersion() (string, error)
	Web3Sha3(data []byte) (string, error)
	NetVersion() (string, error)
	NetListening() (bool, error)
	NetPeerCount() (int, error)
	AsimovProtocolVersion() (string, error)
	AsimovSyncing() (*Syncing, error)
	AsimovCoinbase() (string, error)
	AsimovMining() (bool, error)
	AsimovHashrate() (int, error)
	AsimovGasPrice() (big.Int, error)
	AsimovAccounts() ([]string, error)
	AsimovBlockNumber() (int, error)
	AsimovGetBalance(address, block string) (big.Int, error)
	AsimovGetStorageAt(data string, position int, tag string) (string, error)
	AsimovGetTransactionCount(address, block string) (int, error)
	AsimovGetBlockTransactionCountByHash(hash string) (int, error)
	AsimovGetBlockTransactionCountByNumber(number int) (int, error)
	AsimovGetUncleCountByBlockHash(hash string) (int, error)
	AsimovGetUncleCountByBlockNumber(number int) (int, error)
	AsimovGetCode(address, block string) (string, error)
	AsimovSign(address, data string) (string, error)
	AsimovSendTransaction(transaction T) (string, error)
	AsimovSendRawTransaction(data string) (string, error)
	AsimovCall(transaction T, tag string) (string, error)
	AsimovEstimateGas(transaction T) (int, error)
	AsimovGetBlockByHash(hash string, withTransactions bool) (*Block, error)
	AsimovGetBlockByNumber(number int, withTransactions bool) (*Block, error)
	AsimovGetTransactionByHash(hash string) (*Transaction, error)
	AsimovGetTransactionByBlockHashAndIndex(blockHash string, transactionIndex int) (*Transaction, error)
	AsimovGetTransactionByBlockNumberAndIndex(blockNumber, transactionIndex int) (*Transaction, error)
	AsimovGetTransactionReceipt(hash string) (*TransactionReceipt, error)
	AsimovGetCompilers() ([]string, error)
	AsimovNewFilter(params FilterParams) (string, error)
	AsimovNewBlockFilter() (string, error)
	AsimovNewPendingTransactionFilter() (string, error)
	AsimovUninstallFilter(filterID string) (bool, error)
	AsimovGetFilterChanges(filterID string) ([]Log, error)
	AsimovGetFilterLogs(filterID string) ([]Log, error)
	AsimovGetLogs(params FilterParams) ([]Log, error)
}

var _ AsimovAPI = (*AsimovRPC)(nil)
